version: '3'
services:
  gateway-dev:
    build:
      context: ./Gateway/
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./Gateway/:/app
    ports:
      - "7080:8080"
    networks:
        - red-dev
  estaciones-service-dev:
    build:
      context: ./components/EstacionService/
      dockerfile: ./Dockerfile.dev
    ports:
      - "5070:5048"
    volumes:
      - ./components/EstacionService/:/app/
    networks:
      - red-dev 
  alquileres-service-dev:
    build:
      context: ./components/AlquilerService/
      dockerfile: Dockerfile.dev
    ports:
      - "5054:5053"
    volumes:
      - ./components/AlquilerService/:/app/
    networks:
      - red-dev
  bicicletas-db-dev:
    image: postgres
    ports:
      - "5439:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
      - ./db/backup/:/docker-entrypoint-initdb.d/
      #- ./db/data-dev2/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - red-dev

    
networks:
  red-dev:
    driver: bridge
    #external: true
volumes:
  db-data-dev:
