version: '3.1'
services:
  estaciones-service:
    build:
      context: ./components/EstacionWebApi
      dockerfile: ./Dockerfile
    ports:
      - "80"
    networks:
      - alquileres-production
  bicicletas-db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=password 
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
     - alquileres-production

networks:
  alquileres-production:
