version: '3.1'
services:
  estaciones-service:
    build:
      context: ./components/EstacionWebApi
      dockerfile: ./Dockerfile
    ports:
      - "5180:80"
    networks:
      - alquileres-production
  bicicletas-db:
    #build:
    #  context: ./db/
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=password 
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/backup/:/docker-entrypoint-initdb.d/
    networks:
      - alquileres-production

networks:
  alquileres-production:

volumes:
  db-data:
