version: '3'
services:
  estaciones-service-dev:
    build:
      context: ./components/EstacionWebApi/
      dockerfile: ./Dockerfile.dev
    ports:
      - "5070:5048"
    volumes:
      - ./components/EstacionWebApi/:/app
    networks:
      - red-dev 
  bicicletas-db-dev:
    image: postgres
    ports:
      - "5439:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
      - ./db/backup/:/docker-entrypoint-initdb.d/
      #- ./db/data-dev2/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - red-dev

    
networks:
  red-dev:
    driver: bridge
    #external: true
volumes:
  db-data-dev:
