--
-- PostgreSQL database dump
--

--
-- Name: estaciones; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE estaciones;


ALTER DATABASE estaciones OWNER TO postgres;

\connect estaciones

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;
--
-- Name: estaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estaciones (
    id integer NOT NULL,
    nombre character varying(100),
    fecha_hora_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    latitud double precision,
    longitud double precision
);


ALTER TABLE public.estaciones OWNER TO postgres;

--
-- Name: estaciones_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: estaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estaciones (id, nombre, fecha_hora_creacion, latitud, longitud) FROM stdin;
1	UTN	2023-10-03 21:22:30	-31.442961123175007	-64.19409112111947
2	Comedor	2023-10-03 21:25:12	-31.439612445060444	-64.189333639292
3	Arquitectura	2023-10-03 21:25:12	-31.437872146162334	-64.19105812298827
4	Exactas	2023-10-03 21:40:12	-31.43502451876156	-64.193653947581
5	Jockey	2023-10-03 21:40:12	-31.450717994021375	-64.18122763298067
6	Las Flores	2023-10-03 21:40:12	-31.450822134890547	-64.20046859625478
7	Arco	2023-10-03 21:40:12	-31.437432139835902	-64.12813650438935
8	Parque Sarmiento	2023-10-03 21:40:12	-31.43073667198552	-64.17697332446679
9	Fuerza Aérea	2023-10-03 21:40:12	-31.43058698978064	-64.21691479834789
10	Plaza España	2023-10-03 21:40:12	-31.42851620739036	-64.18475904990146
11	Buen Pastor	2023-10-03 21:40:12	-31.42385497953068	-64.18670883955308
12	San Martín	2023-10-03 21:40:12	-31.416587739294258	-64.18375675702735
13	Terminal	2023-10-03 21:40:12	-31.42218194473781	-64.17529908158092
14	Plaza Colón	2023-10-03 21:40:12	-31.409108235198808	-64.19577990736956
15	General Paz	2023-10-03 21:40:12	-31.411236180411983	-64.1570540082874
16	Kempes	2023-10-03 21:40:12	-31.3682945127801	-64.24559910691622
17	Villa Cabrera	2023-10-03 21:40:12	-31.383393789385238	-64.2133259589045
18	Gral. Bustos	2023-10-03 21:40:12	-31.389057292916398	-64.17237351083637
19	Molinos	2023-12-08 17:48:49.348864	-31.837872146162333	-64.12105812298827
20	Puente Madero	2023-12-08 19:37:01.394903	-31.137872146162334	-64.72105812298827
\.

--
-- Name: estaciones_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estaciones_id_seq', 21, true);

--
-- Name: estaciones estaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estaciones
    ADD CONSTRAINT estaciones_pkey PRIMARY KEY (id);
--
-- PostgreSQL database dump complete
--
