version: '3'
services:
  bicicletas-db-dev:
    #build:
     # context: . 
     # dockerfile: ./Dockerfile.dev
    image: postgres
    ports:
      - "5437:5432"
    volumes:
      - ./backup/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=password
